CREATE DATABASE IF NOT EXISTS schokoladefabrik CHAR SET 'utf8';

DROP TABLE IF EXISTS vorfuehrung;
DROP TABLE IF EXISTS kunstschau;
DROP TABLE IF EXISTS lagerung;
DROP TABLE IF EXISTS bedienung;
DROP TABLE IF EXISTS auftragsinfo;
DROP TABLE IF EXISTS produktionsauftrag;
DROP TABLE IF EXISTS produktion;
DROP TABLE IF EXISTS kunstwerk;
DROP TABLE IF EXISTS standardsortiment;
DROP TABLE IF EXISTS mitarbeiter;
DROP TABLE IF EXISTS kuenstler;
DROP TABLE IF EXISTS firma;
DROP TABLE IF EXISTS lager;
DROP TABLE IF EXISTS maschine;
DROP TABLE IF EXISTS produkt;
DROP TABLE IF EXISTS person;