package at.erceggeyer.dezsys08.echo;

/**
* EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Stefan/Desktop/hello/Hello.idl
* Samstag, 14. Februar 2015 15:39 Uhr MEZ
*/

public interface EchoOperations 
{
  String echoString(String mesg);
} // interface EchoOperations
