package at.erceggeyer.dezsys08.echo;

/**
* Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Stefan/Desktop/hello/Hello.idl
* Samstag, 14. Februar 2015 15:39 Uhr MEZ
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
    public String echoString(String msg);
} // interface Echo
