-- Inserts
\i insert-person.sql
\i insert-mitarbeiter.sql
\i insert-kuenstler.sql
\i insert-kunde.sql
\i insert-lager.sql
\i insert-produkt.sql
\i insert-standardsortiment.sql
\i insert-kunstwerk.sql
\i insert-maschine.sql
\i insert-kunstschau.sql
\i insert-kuendigung.sql
\i insert-auftrag.sql
\i insert-bedient.sql
\i insert-betreut.sql
\i insert-enthaelt.sql 
\i insert-erzeugt.sql 
\i insert-zeigt.sql 
\i insert-lagert.sql 
\i testdata.sql
